In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt

In [2]:
#load the data 
sb_data=pd.read_csv(r"superbowl.csv")
sb_data.tail()

,Super Bowl,Coin Toss Outcome,Coin Toss Winner,Game Winner
50,51,Tails,Home Team,Away Team
51,52,Heads,Home Team,Away Team
52,53,Tails,Home Team,Away Team
53,54,Tails,Away Team,Home Team
54,55,Heads,Away Team,Home Team


In [3]:
# Check the counts of each coin toss winner
sb_data["Coin Toss Winner"].value_counts()

Coin Toss Winner
Away Team    30
Home Team    25
Name: count, dtype: int64

In [4]:
# Check the counts of each game winner
sb_data["Game Winner"].value_counts()

Game Winner
Away Team    31
Home Team    24
Name: count, dtype: int64

In [ ]:
#based on the coin toss winner we can say its not a fair coin

In [7]:
coin_toss_counts = sb_data["Coin Toss Winner"].value_counts().values

In [10]:
fair_coin_expected=[sum(coin_toss_counts)/2,sum(coin_toss_counts)/2]
fair_coin_expected

[np.float64(27.5), np.float64(27.5)]

In [16]:
fair_coin_observed = coin_toss_counts
fair_coin_observed

array([30, 25])

In [13]:
fair_coin_results=stats.chisquare(fair_coin_observed,fair_coin_expected)
fair_coin_results

Power_divergenceResult(statistic=np.float64(0.45454545454545453), pvalue=np.float64(0.5001842570707944))

In [18]:
game_winner_counts = sb_data["Game Winner"].value_counts().values
game_winner_counts

array([31, 24])

In [19]:
game_winner_expected=[sum(game_winner_counts)/2,sum(game_winner_counts)/2]
game_winner_expected

[np.float64(27.5), np.float64(27.5)]

In [20]:
game_winner_observed = game_winner_counts
game_winner_observed

array([31, 24])

In [21]:
game_winner_results=stats.chisquare(game_winner_observed,game_winner_expected)
game_winner_results

Power_divergenceResult(statistic=np.float64(0.8909090909090909), pvalue=np.float64(0.34523107177184))

In [23]:
nfl_games=pd.read_csv(r"nfl_games.csv")
nfl_games.head()

,date,season,neutral,playoff,team1,team2,elo1,elo2,elo_prob1,score1,score2,result1
0,1920-09-26,1920,0,0,RII,STP,1503.947,1300.000,0.824651,48,0,1.0
1,1920-10-03,1920,0,0,AKR,WHE,1503.420,1300.000,0.824212,43,0,1.0
2,1920-10-03,1920,0,0,RCH,ABU,1503.420,1300.000,0.824212,10,0,1.0
3,1920-10-03,1920,0,0,DAY,COL,1493.002,1504.908,0.575819,14,0,1.0
4,1920-10-03,1920,0,0,RII,MUN,1516.108,1478.004,0.644171,45,0,1.0


In [24]:
# Narrow to relevant rows
nfl_games = nfl_games[(nfl_games["neutral"] == 0) & (nfl_games["playoff"] == 0) & (nfl_games["season"] >= 1966 )]
# Engineer a new feature
nfl_games.loc[nfl_games["result1"] == 0, "Game Winner"] = "Away Team"
nfl_games.loc[nfl_games["result1"] == 1, "Game Winner"] = "Home Team"

game_winner_counts_nfl = nfl_games["Game Winner"].value_counts().sort_index()
game_winner_counts_nfl

Game Winner
Away Team    5265
Home Team    7066
Name: count, dtype: int64

In [25]:
nfl_expected = [sum(game_winner_counts_nfl)/2, sum(game_winner_counts_nfl)/2]
nfl_expected

[6165.5, 6165.5]

In [ ]:
nfl_chisquare=stats.chisquare(game_winner_counts_nfl, nfl_expected)
nfl_chisquare
#based on this how do we conclude 
#p-value is less than 0.05 so we reject the null hypothesis
#and thus hometeam have advantage

Power_divergenceResult(statistic=np.float64(263.0444408401589), pvalue=np.float64(3.723190824055013e-59))

In [ ]:
#is winning the game relatted to winning the coin toss
#what is the hypothesis here
#null hypothesis: there is no relation between winning the coin toss and winning the game
#alternate hypothesis: there is a relation between winning the coin toss and winning the game

In [27]:
independence_table = pd.crosstab(sb_data["Coin Toss Winner"], sb_data["Game Winner"])
independence_table

Game Winner,Away Team,Home Team
Coin Toss Winner,,
Away Team,15,15
Home Team,16,9


In [29]:
chi2, p, dof, expected = stats.chi2_contingency(independence_table)
print(chi2, p, dof, expected)

0.5920138888888885 0.44164141533080714 1 [[16.90909091 13.09090909]
 [14.09090909 10.90909091]]
